package info.isaaclee.lolgoitne.core.application.service.riot.exceptions

class SummonerNotFoundException: Exception("match_not_found") {
}
