package info.isaaclee.lolgoitne.core.application.service.riot.exceptions

class SummonerNotFoundException: RuntimeException("summoner_not_found") {
}
